Bootstrap/Models/purchase.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace Bootstrap.Models
{
    public class purchase
    {

        [Required(ErrorMessage = "Please Select a Plan")]
        public int plan { get; set; }
        [Required(ErrorMessage ="Email Address is Required")]
        public string email { get; set; }
        [Required(ErrorMessage = "Password is Required")]
        public string password { get; set; }
        [Required(ErrorMessage = "Confirmation is Required")]
        [CompareAttribute("password", ErrorMessage = "Passwords do not match")]
        public string confirmPassword { get; set; }
        [Required]
        [CompareAttribute("email", ErrorMessage = "Emails do not match")]
        public string confirmEmail { get; set; }
        [Required(ErrorMessage="Please enter a valid card number")]
        [StringLength(16, ErrorMessage="This is not a valid card number, contains too many digits")]
        public string cardNumber { get; set; }
        [Required(ErrorMessage = "Please the full name that appears on your card")]
        public string cardHolderName { get; set; }
        [Required(ErrorMessage = "Exprire Month is Required")]
        public string expiryMonth { get; set; }
        [Required(ErrorMessage = "Exprire Year is Required")]
        public string expiryYear { get; set; }
        [Required(ErrorMessage = "CVV Code is Required")]
        public string cvv { get; set; }
        public bool offers { get; set; }
        [Required(ErrorMessage = "Please Aggree to our terms of use")]
        public bool terms { get; set; }
        public string total { get; set; }
    }
}

Bootstrap/Models/purchaseupgrade.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace Bootstrap.Models
{
    public class purchaseupgrade
    {

        [Required(ErrorMessage = "Please Select a Plan")]
        public int plan { get; set; }
        [Required(ErrorMessage="Please enter a valid card number")]
        [StringLength(16, ErrorMessage="This is not a valid card number, contains too many digits")]
        public string cardNumber { get; set; }
        [Required(ErrorMessage = "Please the full name that appears on your card")]
        public string cardHolderName { get; set; }
        [Required(ErrorMessage = "Exprire Month is Required")]
        public string expiryMonth { get; set; }
        [Required(ErrorMessage = "Exprire Year is Required")]
        public string expiryYear { get; set; }
        [Required(ErrorMessage = "CVV Code is Required")]
        public string cvv { get; set; }
        public bool offers { get; set; }
        [Required(ErrorMessage = "Please Aggree to our terms of use")]
        public bool terms { get; set; }
        public string total { get; set; }
    }
}

Bootstrap/Models/signup.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace Bootstrap.Models
{
    public class signup
    {

        [Required(ErrorMessage = "Please Select a Plan")]
        public int plan { get; set; }
        [Required(ErrorMessage ="Email Address is Required")]
        public string email { get; set; }
        [Required(ErrorMessage = "Password is Required")]
        public string password { get; set; }
        [Required(ErrorMessage = "Confirmation is Required")]
        [CompareAttribute("password", ErrorMessage = "Passwords do not match")]
        public string confirmPassword { get; set; }
        [Required]
        [CompareAttribute("email", ErrorMessage = "Emails do not match")]
        public string confirmEmail { get; set; }
        public bool offers { get; set; }
        [Required(ErrorMessage = "Please Aggree to our terms of use")]
        public bool terms { get; set; }
        
    }
}

Bootstrap/Controllers/StartController.cs
using Bootstrap.Helpers;
using Bootstrap.Models;
using HtmlAgilityPack;
using MailChimp;
using MailChimp.Helper;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.Owin.Security;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Bootstrap.Controllers
{
    public class StartController : Controller
    {
        // GET: Start

         public StartController()
            : this(new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext())))
        {
        }

        public StartController(UserManager<ApplicationUser> userManager)
        {
            UserManager = userManager;
        }

        public UserManager<ApplicationUser> UserManager { get; private set; }

        public ActionResult Index()
        {

            
            return View();
        }

        public ActionResult FreeTrial()
        {
            
            

            return View();
        }
        [HttpPost]
        public ActionResult Test()
        {

            FreeTrials ft = new FreeTrials();
            int ftl = ft.TriesLeft(Request.UserHostAddress);

            if (ftl == 0)
            {
                return Json(new { result = 0 });
            }
            else
            {
                return Json(new { result = 1 });

            }

        }

        public ActionResult FreeTrialLander ()
        {

            return View();
        }
        
        [HttpPost]
        [ValidateInput(false)] 
        public ActionResult FreeTrial(string resume, string job, bool sample)
        {
            if(sample == true)
            {
                return RedirectToAction("FreeTrialLander");
            }
            else
            {

                FreeTrials ft = new FreeTrials();
                int ftl = ft.TriesLeft(Request.UserHostAddress);

                if (ftl == 0)
                {
                    return RedirectToAction("Redirect");
                }
                else
                {



                    Cleaner clean = new Cleaner();
                    string cleanJob = clean.CleanInput(job);
                    string cleanResume = clean.CleanInput(resume);

                    SovrenHelper resumexml = new SovrenHelper();
                    string rxml = resumexml.GetResumeXML(cleanResume);


                    SovrenJob jobxml = new SovrenJob();
                    string xml = jobxml.GetJobXml(cleanJob);
                    Job outJob = new Job();
                    Resume outResume = new Resume();

                    outResume.Competencies = resumexml.GetCompetencies(rxml);
                    outResume.Education = resumexml.GetEducation(rxml);
                    outResume.Experience = resumexml.GetExperience(rxml);
                    outResume.SingleValues = resumexml.GetResumeArray(rxml);


                    outJob = jobxml.GetJobArray(xml);


                    Analyze analysis = new Analyze();
                    Results result = new Results();

                    analysis = result.Compare(outJob, outResume);
                    analysis.JobRaw = job;
                    analysis.ResumeRaw = resume;
                    int ul = ft.IncrementTries(Request.UserHostAddress);
                    TempData["analysis"] = analysis;
                    return RedirectToAction("Results");
                }
            }
        }

        public ActionResult Results()
        {
            Analyze analysis = new Analyze();
            analysis = TempData["analysis"] as Analyze;
            return View(analysis);
        }

        
        public ActionResult Redirect()
        {

            return View();
        }

        public ActionResult Pricing()
        {

            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> SignUp(signup model)
        {
            if (ModelState.IsValid)
            {
                Merchant trans = new Merchant();

                PurchaseSummary transaction = new PurchaseSummary();
                

                IdentityResult userresult = new IdentityResult();
                ApplicationUser user = new ApplicationUser();

                //MerchantResponse result = new MerchantResponse();
                //result.IsTransactionApproved = true;


                string[] plans = { "NA", "Trial", "Monthly", "Extended" };
                ApplicationDbContext db = new ApplicationDbContext();
                using (var dbContextTransaction = db.Database.BeginTransaction())
                {

                    try
                    {

                        if (model.offers != true)
                        {
                            model.offers = false;
                        }

                        //set up users profile

                        ApplicationDbContext.UserProfile up = new ApplicationDbContext.UserProfile();
                        up.EmailAddress = model.email;
                        up.UserName = model.email;
                        up.Plan1 = model.plan.ToString();
                        up.IpAddress = HttpContext.Request.UserHostAddress;
                        up.CreatedDate = DateTime.Now;
                        up.Offers = model.offers;
                        if (model.plan == 3)
                        {
                            up.PlanExperation = DateTime.Now.AddMonths(3);
                        }
                        else
                        {
                            up.PlanExperation = DateTime.Now.AddMonths(1);
                        }
                        up.Terms = model.terms;

                        int toks = 5;
                        
                        up.Tokens = toks;
                        //save entity
                        db.UserProfiles.Add(up);

                        // make it ok to use email UI//
                        var userValidator = UserManager.UserValidator as UserValidator<ApplicationUser>;
                        userValidator.AllowOnlyAlphanumericUserNames = false;


                        //create asp.net user
                        user = new ApplicationUser() { UserName = model.email };
                        userresult = await UserManager.CreateAsync(user, model.password);

                        if (userresult.Succeeded)
                        {
                           
                                ApplicationDbContext.ActionItem a = new ApplicationDbContext.ActionItem();

                                a.PromoId = model.plan;
                                a.UserName = up.UserName;
                                a.UserId = 0;
                                a.PurchaseDate = DateTime.Now;
                                a.Expiration = DateTime.Now.AddMonths(1);
                                db.ActionItems.Add(a);
                                transaction.username = user.UserName;
                                transaction.email = user.UserName;
                                transaction.orderNumber = a.TransactionId;
                                transaction.plan = plans[Convert.ToInt32(model.plan)];
                                transaction.password = model.password;
                                transaction.offers = model.offers;

                                transaction.tokens = up.Tokens;
                                transaction.total = "$0.00";
                                transaction.tokenSummary = "Tokens Purchased: " + up.Tokens;
                                TempData["transaction"] = transaction;
                                db.SaveChanges();
                                dbContextTransaction.Commit();

                                await SignInAsync(user, isPersistent: false);
                                //send welcome email
                                Messenger emailit = new Messenger();
                                string smtpresponse = emailit.SendWelcomeMessageFree(transaction);
                                //MailChimpManager mc = new MailChimpManager("267d9c698c4a9baa3ddc607dd7a1f01c-us7");

                                ////  Create the email parameter
                                //EmailParameter email = new EmailParameter()
                                //{
                                //    Email = model.email
                                    
                                //};

                                //EmailParameter results = mc.Subscribe("f9d9c2c74a", email, null, "html",false,false,false,false);
                                return RedirectToAction("OrderCompleteFree");
                          

                            }
                        }

                    
                    catch (Exception ex)
                    {
                        ModelState.AddModelError("email", ex);
                        return View(model);
                    }



                }



            }
            ModelState.AddModelError("email", "An Error has occured with your form, please review and try again.");
            return View(model);
                
        }
            
        public ActionResult Purchase()
        {
            var plan = Request["plan"];
            var upgrade = Request["upgrade"];
            ViewBag.plan = plan;
            ViewBag.upgrade = upgrade;
            return View();
        }

        public ActionResult SignUp()
        {
            
            return View();
        }

        public ActionResult PurchaseUpgrade()
        {

            var plan = Request["plan"];
            var upgrade = Request["upgrade"];
            ViewBag.plan = plan;
            ViewBag.upgrade = upgrade;
            return View();
        }

        [HttpPost]

Bootstrap/Views/Start/About.cshtml
@{
    ViewBag.Title = "About | Jobminx";
}

<style>
   

    h1, h2 {
        color: #585858;
        font-family: "Oswald",arial,sans-serif;
        font-size: 42px;
        margin:10px;
    }

    h2 {
        color: #707070;
        font-size: 22px;
    }

    /* unvisited link */
    a:link {
        color: #069505;
        text-decoration: none;
    }

    /* mouse over link */
    a:hover {
        color: #F26522;
    }

    .green {
        color: #069505;
        font-weight: bold;
    }

   
</style>

<div class="container">
    <div class="col-md-8 col-lg-offset-2">
        <ol class="breadcrumb">
            <li><a href="/Start">Home</a></li>
            <li class="active"><a href="#">About Jobminx</a></li>

        </ol>
        <center><h1>What is <span class="green">Jobminx</span> all about?</h1></center>
        <p><span class="green">Jobminx</span> asked jobseekers to tell us about the job search experience and we listened.  We heard you when you said the most frustrating part of the job search is after you’ve hit the “send” button and your resumes are sent out into application oblivion never to be seen again. We at <span class="green">Jobminx</span> couldn’t agree more.  It’s natural to feel frustrated when you’ve spent hours searching online for the perfect job opportunity, sent off your resume, and then… nothing.</p>
        <h2>So what’s really happening behind the send button</h2>
        <p>Unless you have optimized your resume, you may not be sending the correct message to the automated ATS’s (applicant tracking system) that exist purely to screen for specific keywords. In other words, even if you are a qualified candidate for the job, you may be rejected by the ATS simply on the merits of a “bad resume”.</p>
        <p>Google “resume” and you’ll find a plethora of advice on how job seekers should format their resumes to beat the ATS’s in hopes of avoiding the “black hole”. Indeed, many blogs exist and all send a similar message to job seekers; don’t apply to jobs you are not qualified, use job description keywords, keep it simple, and above all - target your resume for each job you are applying.</p>
        <p>We’ve all been in the job market at one time or another and understand the frustration of being rejected by ATS software. We know that it takes a great deal of time and effort to optimize a resume for every job description that you apply to. We know that you would appreciate help figuring out which keywords are relevant to target your resume to a specific job opportunity. And we know it’s important to have confidence that your resume will separate you from the competition before hitting the “submit resume” button.</p>
        <h2>How can <span class="green">Jobminx</span> help you?</h2>
        <p><span class="green">Jobminx.com</span> has an innovative solution that will provide the keywords needed to optimize your resume to a job opportunity.  And this all happens in seconds. Go to the <span class="green">Jobminx</span> app and first tell us about yourself by pasting in your resume. Second, paste in the job description that you are interested in. Push the target button and <span class="green">Jobminx</span> will compare your resume to the job description.  The result is a list of keywords specifically targeted from the job description but missing from your resume. You take it from here.  Select keywords from the list that are relevant to your work experience and add them to your resume. Save the changes to your resume and use this newly targeted resume to apply to the job.</p>
        <h2>Yup it’s that easy!</h2>
        <p><span class="green">Jobminx</span> exists to do one thing… get your resume out of cyberspace and in front of hiring managers. We’re confident that you’ll be getting more interviews in no time!</p>
        <center>
            <div style="margin-top:20px; margin-bottom:50px;">
            
                @Html.ActionLink("Get your Keyword Density Report NOW!", "FreeTrial", null, new { @class = "btn btn-primary btn-lg" })
            </div>
          

        </center>
      

    </div>
</div>

Bootstrap/Views/Start/PurchaseUpgrade.cshtml
@model Bootstrap.Models.purchaseupgrade
@{
    if (ViewBag.plan == "2")
    {
        ViewBag.Title = "Upgrade Monthly | Jobminx";
    }
    if (ViewBag.plan == "3")
    {
        ViewBag.Title = "Upgrade Extended | Jobminx";
    }
    else
    {
        ViewBag.Title = "Upgrade | Jobminx";
    }
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/css/pricingplan.css" rel="stylesheet" />
@using (Html.BeginForm("PurchaseUpgrade", "Start", FormMethod.Post, new { @class = "form-horizontal", @role = "form" }))
{
    @Html.AntiForgeryToken()


   <div class="container" style="margin-top:10px;">
       <div class="col-lg-8 col-sm-offset-2">

           <div class=" panel panel-success">
               <!--<a id="OutOfTokens" data-toggle="modal" href="#myModal" class="btn btn-primary btn-lg">Buy Tokens</a>-->
               <div class="panel-heading" style="background-color:green; color:white;">
                   <p>Upgrade Your Plan</p>
               </div>
               <div class="panel-body">
                   <ol class="breadcrumb">
                       <li><a href="/Start/Pricing">Pricing</a></li>
                       <li class="active">Upgrade</li>
                   </ol>
                  
                   @if (ViewBag.plan == "2")
                   {
                       <div id="selected_plan" style="color:#115f1f"><h3>Selected Plan: Monthly- $24.99</h3></div>
                       <input type="hidden" value="24.99" name="total" id="total" />
                       <input type="hidden" value="2" name="plan" id="plan" />
                   }
                   @if (ViewBag.plan == "3")
                   {
                       <div id="selected_plan" style="color:#115f1f"><h3>Selected Plan: Extended- $59.99</h3></div>
                       <input type="hidden" value="59.99" name="total" id="total" />
                       <input type="hidden" value="3" name="plan" id="plan" />
                   }

                   

                   <div id="cc">
                       <div class="form-group">
                           <label class="col-sm-3 control-label" for="cardHolderName">Name on Card</label>
                           <div class="input-group col-sm-7">
                               @Html.TextBoxFor(model => model.cardHolderName, new { @class = "form-control", @Placeholder = "Enter Cardholder Name" })
                               <span class="input-group-addon default"><span class="glyphicon glyphicon-asterisk"></span></span>

                           </div>
                           <div class="col-sm-9 col-lg-offset-3" style="color:red;">@Html.ValidationMessageFor(m => m.cardHolderName)</div>
                       </div>
                       <div class="form-group">
                           <label class="col-sm-3 control-label" for="cardNumber">Card Number</label>
                           <div class="input-group col-sm-7" data-validate="length" data-length="16">
                               @Html.TextBoxFor(model => model.cardNumber, new { @class = "form-control", @Placeholder = "Enter Card Number" })
                               <span class="input-group-addon default"><span class="glyphicon glyphicon-asterisk"></span></span>

                           </div>
                           <div class="col-sm-9 col-lg-offset-3" style="color:red;">@Html.ValidationMessageFor(m => m.cardNumber)</div>
                       </div>
                       <div class="form-group">
                           <label class="col-sm-3 control-label" for="expiryMonth">Expire Date</label>
                           <div class="input-group col-sm-8">

                               <div class="input-group col-lg-4 pull-left" style="margin-right:5px;">
                                   <select class="form-control" name="expiryMonth" id="validate-select" required>
                                       <option value="">Month</option>
                                       <option value="01">Jan (01)</option>
                                       <option value="02">Feb (02)</option>
                                       <option value="03">Mar (03)</option>
                                       <option value="04">Apr (04)</option>
                                       <option value="05">May (05)</option>
                                       <option value="06">June (06)</option>
                                       <option value="07">July (07)</option>
                                       <option value="08">Aug (08)</option>
                                       <option value="09">Sep (09)</option>
                                       <option value="10">Oct (10)</option>
                                       <option value="11">Nov (11)</option>
                                       <option value="12">Dec (12)</option>
                                   </select>
                                   <span class="input-group-addon default"><span class="glyphicon glyphicon-asterisk"></span></span>
                               </div>

                               <div class="input-group col-lg-4 pull-left" style="margin-right:5px;">
                                   <select class="form-control" name="expiryYear" id="validate-select" required>
                                       <option value="">Year</option>
                                       <option value="13">2013</option>
                                       <option value="14">2014</option>
                                       <option value="15">2015</option>
                                       <option value="16">2016</option>
                                       <option value="17">2017</option>
                                       <option value="18">2018</option>
                                       <option value="19">2019</option>
                                       <option value="20">2020</option>
                                       <option value="21">2021</option>
                                       <option value="22">2022</option>
                                       <option value="23">2023</option>
                                   </select>
                                   <span class="input-group-addon default"><span class="glyphicon glyphicon-asterisk"></span></span>
                               </div>


                           </div>
                           <div class="col-sm-9 col-lg-offset-3" style="color:red;">@Html.ValidationMessageFor(m => m.expiryMonth)</div>
                           <div class="col-sm-9 col-lg-offset-3" style="color:red;">@Html.ValidationMessageFor(m => m.expiryYear)</div>
                       </div>
                       <div class="form-group">
                           <label class="col-sm-3 control-label" for="cvv">Card CVV</label>
                           <div class="input-group col-sm-7">
                               @Html.TextBoxFor(model => model.cvv, new { @class = "form-control", @Placeholder = "Security Code", @required = "required" })
                               <span class="input-group-addon default"><span class="glyphicon glyphicon-asterisk"></span></span>

                           </div>
                           <div class="col-sm-9 col-lg-offset-3" style="color:red;">@Html.ValidationMessageFor(m => m.cvv)</div>
                       </div>
                   </div>

                   <div class="form-group">
                       <label class="col-sm-3 control-label">
                           Special Offers:
                       </label>
                     
                       <div class="col-sm-8">
                           <div class="checkbox">
                               <label>
                                   <input type="checkbox"  name="offers" id="offers" value="true" />like to be sent special offers via email
                               </label>
                           </div>
                   </div>
                       </div>
                   <div class="form-group">
                       <label class="col-sm-3 control-label">
                           Terms of Use:
                       </label>
                      
                       <div class="col-sm-8">
                           <div class="checkbox">
                               <label>
                                   <input type="checkbox"  name="terms" id="terms" value="true" required="required" />I agree to the terms of use
                               </label>
                           </div>
                           
                       </div>
                   </div>



                   <div class="col-lg-8 col-lg-offset-2">


                       <button type="submit" style="width:100%; margin-bottom:10px;" class="btn btn-primary btn-lg">Complete Upgrade</button>
                   </div>



               </div>
           </div>

       </div>
               </div>


                  
           }

           <script>

               $(document).ready(function () {



                   $('.input-group input[required], .input-group textarea[required], .input-group select[required]').on('keyup change', function () {
                       var $form = $(this).closest('form'),
                           $group = $(this).closest('.input-group'),
                           $addon = $group.find('.input-group-addon'),
                           $icon = $addon.find('span'),
                           state = false;

                       if (!$group.data('validate')) {
                           state = $(this).val() ? true : false;
                       } else if ($group.data('validate') == "email") {
                           state = /^([a-zA-Z0-9_\.\-])+\@@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/.test($(this).val())
                       } else if ($group.data('validate') == 'phone') {
                           state = /^[(]{0,1}[0-9]{3}[)]{0,1}[-\s\.]{0,1}[0-9]{3}[-\s\.]{0,1}[0-9]{4}$/.test($(this).val())
                       } else if ($group.data('validate') == "length") {
                           state = $(this).val().length >= $group.data('length') ? true : false;
                       } else if ($group.data('validate') == "number") {
                           state = !isNaN(parseFloat($(this).val())) && isFinite($(this).val());
                       }

                       if (state) {
                           $addon.removeClass('default');
                           $addon.addClass('success');
                           $icon.attr('class', 'glyphicon glyphicon-ok');
                       } else {
                           $addon.removeClass('success');
                           $addon.addClass('default');
                           $icon.attr('class', 'glyphicon glyphicon-asterisk');
                       }

                       if ($form.find('.input-group-addon.danger').length == 0) {
                           $form.find('[type="submit"]').prop('disabled', false);
                       } else {
                           $form.find('[type="submit"]').prop('disabled', true);
                       }
                   });

                   $('.input-group input[required], .input-group textarea[required], .input-group select[required]').trigger('change');


               });

           </script>

Bootstrap/Views/Start/Redirect.cshtml
@{
    ViewBag.Title = "Buy Now";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <div class="row">
        <div class="col-sm-6 col-sm-offset-3">

            <div id="overview" class="panel panel-default">
                <div class="panel-heading" style="background-color:green; color:white;">Alert!</div>
                <div class="panel-body">


                    <h3>Our records indicate that you have aleady used your free trial</h3>

                    <a class="btn btn-primary btn-lg pull-right" href="/Start/Pricing">Buy Now!</a>


                </div>

            </div>
        </div>
    </div>
</div>