Bootstrap/Models/purchaseupgrade.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace Bootstrap.Models
{
    public class purchaseupgrade
    {

        [Required(ErrorMessage = "Please Select a Plan")]
        public int plan { get; set; }
        [Required(ErrorMessage="Please enter a valid card number")]
        [StringLength(16, ErrorMessage="This is not a valid card number, contains too many digits")]
        public string cardNumber { get; set; }
        [Required(ErrorMessage = "Please the full name that appears on your card")]
        public string cardHolderName { get; set; }
        [Required(ErrorMessage = "Exprire Month is Required")]
        public string expiryMonth { get; set; }
        [Required(ErrorMessage = "Exprire Year is Required")]
        public string expiryYear { get; set; }
        [Required(ErrorMessage = "CVV Code is Required")]
        public string cvv { get; set; }
        public bool offers { get; set; }
        [Required(ErrorMessage = "Please Aggree to our terms of use")]
        public bool terms { get; set; }
        public string total { get; set; }
    }
}

Bootstrap/Controllers/MembersController.cs
using Bootstrap.Helpers;
using Bootstrap.Models;
using GemBox.Document;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using iTextSharp.text;
using iTextSharp.text.pdf;
using iTextSharp.text.pdf.parser;
using System.Net;
using HtmlAgilityPack;
using MelissaData;
using System.Data.Services.Client;
using Newtonsoft.Json;
using System.Text.RegularExpressions;

namespace Bootstrap.Controllers
{
    public class MembersController : Controller
    {
        // GET: Members
       
        
        public ActionResult Index()
        {
           
            if(Request["Id"] != null)
            {
                var resumeId = Request["Id"].ToString();
                ApplicationDbContext db = new ApplicationDbContext();
                var q = db.UserResumes.Find(Convert.ToInt32(resumeId));
                ViewBag.resumeText = q.Resume;
                ViewBag.name = q.Name;
                ViewBag.updated = q.DateModified.ToString();
            }
            
            string ip = Request.UserHostAddress.ToString();

            //"108.224.68.67",

            try
            {
                ipcheck ipdata = new ipcheck();
                ipobj ipob = ipdata.getIpData(ip);
                ViewBag.ZipCode = ipob.zipCode;
            }
            catch (Exception ex)
            {
                ViewBag.ZipCode = "NA";
            }
            
            if(User.Identity.IsAuthenticated)
            {
                ApplicationDbContext db = new ApplicationDbContext();
                var q = db.UserProfiles.Where(s => s.UserName == User.Identity.Name).FirstOrDefault();
                ViewBag.plan = q.Plan1;

                if (q.PlanExperation <= DateTime.Now)
                {

                    q.Plan1 = "1";
                    q.Tokens = 5;
                    q.PlanExperation = DateTime.Now.AddMonths(1);
                    db.SaveChanges();

                }
            }
            else
            {

               //user is good to use unlimited

            }
            
            
            

            return View();
        }
        [HttpGet]
        public ActionResult JobAlert()
        {
            if(User.Identity.IsAuthenticated)
            {
                ApplicationDbContext db = new ApplicationDbContext();
                var q = db.UserProfiles.Where(e => e.UserName == User.Identity.Name).SingleOrDefault();
                if(q.JobAlert)
                {
                    return Json(new { result = true }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { result = false }, JsonRequestBehavior.AllowGet);
                }
            }
            else
            {

                return Json(new { result = false }, JsonRequestBehavior.AllowGet);

            }

        }

        [HttpPost]
        public ActionResult SetJobAlert()
        {
            if (User.Identity.IsAuthenticated)
            {
                ApplicationDbContext db = new ApplicationDbContext();
                var q = db.UserProfiles.Where(e => e.UserName == User.Identity.Name).SingleOrDefault();
                q.JobAlert = true;
                db.SaveChanges();
                return Json(new { result = true });
            }
            else
            {
                return Json(new { result = false });
            }


        }

        public ActionResult DeleteResumeConfirm()
        {
            var resumeId = Request["Id"].ToString();
            ViewBag.Id = resumeId;
            return View();
        }

        public ActionResult DeleteResume()
        {

            var resumeId = Request["Id"].ToString();
            ApplicationDbContext db = new ApplicationDbContext();
            var q = db.UserResumes.Find(Convert.ToInt32(resumeId));
            db.UserResumes.Remove(q);
            db.SaveChanges();
            return RedirectToAction("UserProfile");
        }

        public ActionResult Upgrade()
        {

            return View();
        }
      
        [HttpPost]
        public ActionResult Engage(string plan)
        {
            ApplicationDbContext db = new ApplicationDbContext();
            ApplicationDbContext.Engagement ngage = new ApplicationDbContext.Engagement();
            ngage.Plan = plan;
            if(!User.Identity.IsAuthenticated)
            {
                ngage.UserId = "Unkown";
            }
            else
            {
                ngage.UserId = User.Identity.Name;
            }
            
            ngage.Expiration = DateTime.Now;
            db.Engagements.Add(ngage);
            db.SaveChanges();

            return Json(new { result = "added!" });
        }
        
        [HttpPost]
        public ActionResult SaveResume(string text, string rid)
        {
            var nrid = Convert.ToInt32(rid);
            ApplicationDbContext db = new ApplicationDbContext();
            if(nrid != 0 )
            {
                var q = db.UserResumes.Find(nrid);
                q.Resume = text;
                db.SaveChanges();

                return Json(new { result = "success" });
            }
            else
            {
                return Json(new { result = "fail" });
            }

        }

        [HttpPost]
        public ActionResult SaveResumePaste(string text, string zip, string name)
        {
            
            ApplicationDbContext db = new ApplicationDbContext();

            ApplicationDbContext.UserResume u = new ApplicationDbContext.UserResume();
            u.Name = name;
            u.UserId = User.Identity.Name;
            u.Resume = text;
            u.DateModified = DateTime.Now;
            u.DateLoaded = DateTime.Now;
            u.ZipCode = zip;
            u.ContentType = "application/pdf";
            db.UserResumes.Add(u);    
            db.SaveChanges();

            return Json(new { result = "success", id= u.Id });
            
        }

        [HttpPost]
        public ActionResult SaveResumeAs(int id, string name, string zip, string text)
        {

            ApplicationDbContext db = new ApplicationDbContext();
            var or = db.UserResumes.Find(id);

            ApplicationDbContext.UserResume nr = new ApplicationDbContext.UserResume();
            nr.Name = name;
            nr.UserId = User.Identity.Name;
            nr.Resume = text;
            nr.DateModified = DateTime.Now;
            nr.DateLoaded = DateTime.Now;
            nr.ZipCode = zip;
            nr.ContentType = "application/pdf";
            db.UserResumes.Add(nr);
            db.SaveChanges();

            return Json(new { result = "success", id = nr.Id });

        }
        
        public ActionResult GetTokens()
        {
            

            if (!User.Identity.IsAuthenticated)
            {
                FreeTrials ft = new FreeTrials();
                int ftl = ft.TriesLeft(Request.UserHostAddress);
                if (ftl == 0)
                {
                    ViewData["tokens"] = 0;
                    ViewData["plan"] = 1;
                    return PartialView("_GetTokensNon");
                }
                else
                {
                    ViewData["tokens"] = 1;
                    ViewData["plan"] = 1;
                    return PartialView("_GetTokensNon");
                }
            }
            else
            {
                string username = User.Identity.Name;
                ApplicationDbContext db = new ApplicationDbContext();
                var up = db.UserProfiles.Where(m => m.UserName == username).FirstOrDefault();
                var a = db.ActionItems.Where(m => m.UserId == up.UserId).FirstOrDefault();
                ViewBag.firstname = up.FirstName;
                ViewData["expire"] = up.PlanExperation;
                ViewData["plan"] = up.Plan1;
                if (up.Tokens <= 0)
                {
                    up.Tokens = 0;
                }
                if (up.Plan1 == "3" || up.Plan1 == "2")
                {
                    ViewData["tokens"] = 0;
                }
                else
                {
                    ViewData["tokens"] = up.Tokens;
                }

                return PartialView("_GetTokens");
            }
        }

      
        [HttpPost]   
        public ActionResult Report(string resume, string job, int rid)
        {
            if (!User.Identity.IsAuthenticated)
            {

                ApplicationDbContext db = new ApplicationDbContext();
                FreeTrials ft = new FreeTrials();
                int ftl = ft.TriesLeft(Request.UserHostAddress);
                if (ftl == 0)
                {
                    return RedirectToAction("Redirect");
                }
                else
                {

                    string cleanresume = HtmlSanitizer.Sanitize(resume);
                    string cleanjob = HtmlSanitizer.Sanitize(job);


                    SovrenHelper resumexml = new SovrenHelper();
                    string rxml = resumexml.GetResumeXML(cleanresume);


                    SovrenJob jobxml = new SovrenJob();
                    string xml = jobxml.GetJobXml(cleanjob);

                    Job outJob = new Job();
                    Resume outResume = new Resume();

                    outResume.Competencies = resumexml.GetCompetencies(rxml);
                    outResume.Education = resumexml.GetEducation(rxml);
                    outResume.Experience = resumexml.GetExperience(rxml);
                    outResume.SingleValues = resumexml.GetResumeArray(rxml);
                    outResume.Taxonomies = resumexml.GetBestFitTaxonomies(rxml);
                    outResume.BestTax = outResume.Taxonomies.FirstOrDefault();
                    outResume.ResumeText = resume;

                    outJob = jobxml.GetJobArray(xml);

Bootstrap/Views/Members/BuyTokens.cshtml
@model Bootstrap.Models.addTokens

@{
    ViewBag.Title = "Buy Tokens | Jobminx";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/css/pricingplan.css" rel="stylesheet" />
@using (Html.BeginForm("BuyTokens", "Members", FormMethod.Post, new { @class = "form-horizontal", @role = "form" }))
{
    @Html.AntiForgeryToken()
    <div class="container">
        <h1 class="oswald text-center">Select your plan and let <span style="color:green"><b>Jobminx</b></span> optimize your resume TODAY!</h1>
        <br />
        <div class="col-lg-12">
            <div class="row flat">
                <div class="col-sm-2 col-sm-offset-3">
                    <ul class="plan plan1">
                        <li class="plan-name">
                            Starter
                        </li>
                        <li class="plan-price">
                            <input type="radio" name="plan" class="plan" value="1">
                            <label class="desc">
                                Target and optmize your resume for <b>5</b> unique job descriptions.
                            </label>
                        </li>

                        <li class="plan-action">
                            <b style="font-size:14px; line-height:.5em">JUST $6.99</b>
                        </li>
                    </ul>
                </div>
                <div class="col-sm-2">
                    <ul class="plan plan1 featured">
                        <li class="plan-name">
                            Plus
                            <img class="mp pull-right" style="width:70px;" src="~/Content/mp.gif" />
                        </li>
                        <li class="plan-price">
                            <input type="radio" name="plan" class="plan" value="2" checked>
                            <label class="desc">
                                Target and optmize your resume for <b>25</b> unique job descriptions.
                            </label>
                        </li>

                        <li class="plan-action">
                            <b style="font-size:14px; line-height:.5em">ONLY $24.99</b>
                            
                        </li>
                    </ul>
                </div>
                <div class="col-sm-2">
                    <ul class="plan plan1">
                        <li class="plan-name">
                            Unlimited

                        </li>
                        <li style="color:green; margin-top:-50px; font-size:10px;">Unlimited use of our Keyword Resume Editor</li>
                        <li class="plan-price">
                            <input type="radio" name="plan" class="plan" value="3">
                            <label class="desc">
                                Target and optmize your resume for <b>Unlimited</b> unique job descriptions for 30 days.

                            </label>
                        </li>

                        <li class="plan-action">
                            <b style="font-size:14px; line-height:.5em">ONLY $49.99</b>
                        </li>
                    </ul>
                </div>

            </div>

        </div>

    </div> <!-- /container -->
    <div class="container" style="margin-top:20px;">
        <div class="col-lg-6 col-sm-offset-3">
            <div id="selected_plan" style="color:#115f1f"><h3>Selected Plan: Plus- $24.99</h3></div>


            <h2>Add Tokens</h2>
            
            <hr />
            <input type="hidden" name="email" id="email" value="@User.Identity.Name" />

            <input type="hidden" value="24.99" name="total" id="total" />
           
            <div class="form-group">
                <label class="col-sm-3 control-label" for="cardHolderName">Name on Card</label>
                <div class="col-sm-9">
                    <input type="text" class="form-control" name="cardHolderName" id="cardHolderName" placeholder="Card Holder's Name">
                    <div style="color:red;">@Html.ValidationMessageFor(m => m.cardHolderName)</div>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label" for="cardNumber">Card Number</label>
                <div class="col-sm-9">
                    <input type="text" class="form-control" name="cardNumber" id="cardNumber" placeholder="Debit/Credit Card Number">
                    <div style="color:red;">@Html.ValidationMessageFor(m => m.cardNumber)</div>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label" for="expiryMonth">Expiration Date</label>
                <div class="col-sm-9">
                    <div class="row">
                        <div class="col-xs-3">
                            <select class="form-control col-sm-2" name="expiryMonth" id="expiryMonth">
                                <option>Month</option>
                                <option value="01">Jan (01)</option>
                                <option value="02">Feb (02)</option>
                                <option value="03">Mar (03)</option>
                                <option value="04">Apr (04)</option>
                                <option value="05">May (05)</option>
                                <option value="06">June (06)</option>
                                <option value="07">July (07)</option>
                                <option value="08">Aug (08)</option>
                                <option value="09">Sep (09)</option>
                                <option value="10">Oct (10)</option>
                                <option value="11">Nov (11)</option>
                                <option value="12">Dec (12)</option>
                            </select>
                        </div>

                        <div class="col-xs-3">
                            <select class="form-control" name="expiryYear">
                                <option value="13">2013</option>
                                <option value="14">2014</option>
                                <option value="15">2015</option>
                                <option value="16">2016</option>
                                <option value="17">2017</option>
                                <option value="18">2018</option>
                                <option value="19">2019</option>
                                <option value="20">2020</option>
                                <option value="21">2021</option>
                                <option value="22">2022</option>
                                <option value="23">2023</option>
                            </select>
                        </div>
                        <div style="color:red;">@Html.ValidationMessageFor(m => m.expiryMonth)</div>
                        <div style="color:red;">@Html.ValidationMessageFor(m => m.expiryYear)</div>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label" for="cvv">Card CVV</label>
                <div class="col-sm-9">
                    <input type="text" class="form-control" name="cvv" id="cvv" placeholder="Security Code">
                    <div style="color:red;">@Html.ValidationMessageFor(m => m.cvv)</div>
                </div>

            </div>


         
            <div class="form-group">

                <div class="col-sm-8 col-lg-offset-4">

                    <button type="submit" class="btn btn-primary btn-lg" style="width:200px; margin-left:auto; margin-right:auto;">Pay Now</button>
                </div>
            </div>


        </div>
    </div>
}

<script>

    $(document).ready(function () {

        $("#alert").hide();

        $("input:radio[name=plan]").click(function () {

            var value = $(this).val();
            var total = "0";
            if (value == "1") {
                value = "<h3>Selected Plan: Starter - $6.99</h3>";
                total = "6.99";
                $("#total").val(total);
            }

            if (value == "2") {
                value = "<h3>Selected Plan: Plus- $24.99</h3>";
                total = "24.99";
                $("#total").val(total);
            }

            if (value == "3") {
                value = "<h3>Selected Plan: Unlimited- $49.99</h3>";
                total = "49.99";
                $("#total").val(total);
            }

            $("#selected_plan").html(value);

        });


    });

</script>

Bootstrap/Views/Members/DeleteResumeConfirm.cshtml
@{
    ViewBag.Title = "DeleteResumeConfirm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-sm-6 col-sm-offset-3">

            <div id="overview" class="panel panel-default">
                <div class="panel-heading" style="background-color:green; color:white;">Are you sure you want to delete this resume?</div>
                <div class="panel-body">


                    

                    <a class="btn btn-danger btn-lg pull-right" style="color:white;" href="/Members/DeleteResume?Id=@ViewBag.Id">Delete</a>
                    <a class="btn btn-primary btn-lg pull-right" href="/Members/UserProfile#Resumes">Cancel</a>


                </div>

            </div>
        </div>
    </div>
</div>

Bootstrap/Views/Members/OrderComplete.cshtml
@model Bootstrap.Models.PurchaseSummary

@{
    ViewBag.Title = "OrderComplete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>

    .items {
        margin-bottom:3px;
        margin-top:3px;
    }
</style>
<div class="container">
    <div class="row">

        <div class="col-sm-12">
            <h2 class="text-center animated fadeInDown">Thank You For Your Puchase!</h2>
            <div class="text-center actions animated fadeInDown delay2">



                <div class="col-sm-10 col-sm-offset-1" style="text-align:left;">

                    <div class="col-sm-6">
                        <div class=" panel panel-default">
                            <div class="panel-heading">Today's Purchase Details</div>
                            <div class="panel-body">
                                <div style="margin:10px;">
                                  <p class="items"><b>Order Confermation Nummber:</b> @Model.orderNumber</p>
                                    <p class="items"><b>Transaction Summaary</b></p>
                                    <div id="t_summary" style="height:200px; width:100%; overflow-y:scroll;">
                                        @Model.ctr
                                    </div>
                                    <p class="items"><b>Date:</b> @DateTime.Now.ToShortDateString()</p> 

                                </div>
                              
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="panel panel-default">
                            <div class="panel-heading">User Profile</div>
                            <div class="panel-body">
                                <p class="items"><b>User Name:</b> @Model.username</p>
                                <p class="items"><b>Email Address:</b> @Model.username</p>
                               

                                <div class="well" style="height:125px;">
                                    <div class="text-center">
                                    <p class="items">You Currently Have <span style="color:green;"><b>@Model.tokens</b></span> Tokens In Your Account.</p>
                                        <center>
                                            <a href="/Members" style="margin:5px;" class="btn btn-primary pull-left">Start a New Report</a>
                                            
                                        </center>
                                    </div>

                                
                            </div>
                        </div>
                    </div>

                </div>


               


            </div>

        </div>

    </div>

</div>
</div>

Bootstrap/Views/Members/Upgrade.cshtml
@{
    ViewBag.Title = "Plan Upgrade | Jobminx";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/css/pricingplan.css" rel="stylesheet" />

<div class="container">
    <h1 class="oswald text-center">Upgrade Now!</h1>
    <h3 class="oswald text-center">Select the plans that's right for you and start optimizing TODAY.</h3>
   <br/>
    <div class="col-lg-10 col-lg-offset-1">
       
       
        <div class="col-md-6">
            <div class="panel panel-success">
                <div class="panel-heading">
                    <h4 class="text-center">
                        <span class="oswald text-center">Monthly Plan</span>
                        <img class="mp pull-right" style="width:91px;" src="~/Content/mp.png" />
                    </h4>
                </div>
                <div class="panel-body text-center">
                    <div class="lead">
                        <strong>$24.99 per month</strong><br/>
                        <p><strong>Unlimited</strong> - Resume to Job Description Comparisons</p>
                        <p><strong>Unlimited</strong> - Keyword Reports</p>
                        <p><strong>Including:</strong></p>
                    </div>
                </div>
                <ul class="list-group list-group-flush text-center">
                    <li class="list-group-item"><i class="glyphicon glyphicon-ok"></i> Hiring Manager Summary</li>
                    <li class="list-group-item"><i class="glyphicon glyphicon-ok"></i> Key Skill Density Analysis</li>
                    <li class="list-group-item"><i class="glyphicon glyphicon-ok"></i> Years of Experience Analysis</li>
                    <li class="list-group-item"><i class="glyphicon glyphicon-ok"></i> Education Analysis</li>
                    <li class="list-group-item"><i class="glyphicon glyphicon-ok"></i> <strong>Unlimited</strong>- Resume Editor <br/>Real-time Resume Optimization</li>
                    <li class="list-group-item">
                        <i class="glyphicon glyphicon-ok"></i> <strong>Unlimited</strong> - Job Recommendations <br/>Job matches based on Resume<br/>Job matches similar to job chosen</li>
                </ul>
                <div class="panel-footer">
                    <a href="/Start/PurchaseUpgrade?plan=2&upgrade=1" class="btn btn-lg btn-block btn-success">BUY NOW!</a>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="panel panel-success">
                <div class="panel-heading">
                    <h4 class="text-center">
                        <span class="oswald text-center">Extended Plan</span>
                        <img class="mp pull-right" style="width:91px;" src="~/Content/bv.png" />
                    </h4>
                </div>
                <div class="panel-body text-center">
                    <div class="lead">
                        <strong>59.99 for 3 Months</strong><br/>
                        <p><strong>Unlimited</strong> - Resume to Job Description Comparisons</p>
                        <p><strong>Unlimited</strong> - Keyword Reports</p>
                        <p><strong>Including Unlimited:</strong></p>
                    </div>
                </div>
                <ul class="list-group list-group-flush text-center">
                    <li class="list-group-item"><i class="glyphicon glyphicon-ok"></i> Hiring Manager Summary</li>
                    <li class="list-group-item"><i class="glyphicon glyphicon-ok"></i> Key Skill Density Analysis</li>
                    <li class="list-group-item"><i class="glyphicon glyphicon-ok"></i> Years of Experience Analysis</li>
                    <li class="list-group-item"><i class="glyphicon glyphicon-ok"></i> Education Analysis</li>
                    <li class="list-group-item"><i class="glyphicon glyphicon-ok"></i> <strong>Unlimited</strong>- Resume Editor <br />Real-time Resume Optimization</li>
                    <li class="list-group-item">
                        <i class="glyphicon glyphicon-ok"></i> <strong>Unlimited</strong> - Job Recommendations <br />Job matches based on Resume<br />Job matches similar to job chosen
                    </li>
                </ul>
                <div class="panel-footer">
                    <a href="/Start/PurchaseUpgrade?plan=3&upgrade=1" class="btn btn-lg btn-block btn-success">BUY NOW!</a>
               </div>
            </div>
        </div>
      
     

    </div>
    
</div>

    
   